server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpashop?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    
  jpa:
    hibernate:
#    자동으로 table을 만들어주는 모드
# 내가 가지고있는 entity를 지우고 다시 생성
#      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true (system.out으로 출력)
        format_sql: true
         
logging:
  level:
#    로그를 통해서 디버그 출력
# hibernate가 생성하는 sql이 다보임
    org.hibernate.SQL: debug
    #콘솔에서 쿼리문 데이터 출력
    org.hibernate.type: trace
